name: build

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v2
      
      - name: docker-compose up
        run: |
          docker-compose up -d
      
      - name: webpack compile
        run: |
          docker-compose exec -T web rails assets:precompile

      - name: create database
        run: |
          docker-compose exec -T web rails db:create

      - name: exec rspec
        run: |
          docker-compose exec -T web bundle exec rspec
